### ISSUE TITLE
이슈 템플릿 설정 여부

### ISSUE THREAD

**Issue by Dokkabei97** [Dokkabei97/dastargram#12]
풀 리퀘스트시 템플릿이 설정되어 있는데 이슈도 동일하게 템플릿을 만들어 이슈를 통일화 하는거에 대해 어떻게 생각하나요?
댓글 찬반 여부 부탁드립니다.

@hwangjun 
@Yisak5 
@diriring 
@yoonyoon98

**Comment by Yisak5** [comment]
이슈 통일화 전 찬성합니다

**Comment by hwangjun** [comment]
찬성이요~

**Comment by Dokkabei97** [comment]
설정 완료로 종료합니다
